-- 코드를 입력하세요
SELECT 
    B.TITLE, 
    B.BOARD_ID, 
    R.REPLY_ID, 
    R.WRITER_ID, 
    R.CONTENTS, 
    DATE_FORMAT(R.CREATED_DATE, "%Y-%m-%d") 
AS 
    CREATED_DATE
FROM    
    USED_GOODS_BOARD B JOIN USED_GOODS_REPLY R
ON 
    B.BOARD_ID = R.BOARD_ID
WHERE 
    DATE(B.CREATED_DATE)
between '2022-10-01' and '2022-10-31'
ORDER BY 
    R.CREATED_DATE, B.TITLE